### ISSUE TITLE
【bug】运行久了，cmd那边会卡死未响应，powershell会一直重复创建cmd

### ISSUE THREAD

**Issue by 1529960009** [rhwong/qsign-onekey#3]

**Comment by 1529960009** [comment]
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/45947734/922acb3f-114f-41fd-af4d-016097c954e6)

**Comment by huankong233** [comment]
> 确实是bug，目前没有好办法。 由于无法有效获取pid，所以不能准确的杀死希望托管的进程。（考虑到有些服务器上不止一个java，所以也不好直接杀死java） 并且，有些时候虽然程序已经出现了问题，无法提供签名服务，但是api服务也是正常的，这样的话会判断不到。 如果有好办法欢迎提供pr，或者稍后在我合并完新版本后尝试解决。

pid获取应该不难，
~~~ batch
netstat -ano | findstr { port } | findstr LISTENING
~~~
![image](https://github.com/rhwong/unidbg-fetch-qsign-onekey/assets/49610758/c8286696-a02c-4612-bbcf-6dfa57db0717)

**Comment by rhwong** [comment]
跑路了

**Comment by kagangtuya-star** [comment]
尝试解决了下，pr了
