### ISSUE TITLE
qsign无限重启

### ISSUE THREAD

**Issue by Momona0v0** [rhwong/qsign-onekey#46]
版本：qsign-2023-10-25，其中lib文件夹和start_qsign.bat 替换为了最新版本
如图，qsign-core正常运行，但qsign-deamon检测qsign-core没有运行，并无限重启qsign-core
令人费解的是，qsign-deamon和qsign-core 在本人的电脑上（win10）可以正常运行，但是在服务器（windows server2012 R2）上就会出现这种情况。
![QQ图片20231106181442](https://github.com/rhwong/qsign-onekey/assets/131581477/7c2368e8-f1c5-423b-a8a3-3c196ca839d3)

**Comment by Momona0v0** [comment]
另：换回release中的start_qsign.bat后，报OpenJDK Platform binary已停止工作的错误

**Comment by Momona0v0** [comment]
另：回退版本后又出现问题。登录一切正常。在bot发送一句话后，原token立刻失效。自动刷新token时，显示qsign未能初始化，导致获取token失败。于是token返回一个空值，使qsign崩溃。
这是gocq的问题还是qsign的问题？
![QQ图片20231106210604](https://github.com/rhwong/qsign-onekey/assets/131581477/1e1ea90c-020b-425d-a65a-b352e25a2ac0)

**Comment by rhwong** [comment]
是🐧干的。

**Comment by rhwong** [comment]
守护进程和核心脚本反复启动这个确实存在，还在优化中没发上来

**Comment by rhwong** [comment]
qsign反复去世，考虑更换服务器吧，高版本就这样、
来以为有佬给fix了，结果跑起来还是反复去世。

**Comment by Momona0v0** [comment]
给服务器安装了curl并使用最新的start_qsign.bat，qsign崩溃后会自动重启。但是丢token的问题没有解决，导致消息延迟巨大
可恶，没备份，找不到旧版的qsign了。先这样，期待大佬们能想到什么办法。
感谢大佬们一直以来的付出。

**Comment by rakuaki** [comment]
![image](https://github.com/rhwong/qsign-onekey/assets/62581450/2c6c5261-0f0c-4af4-8e40-66064b651ba3)
出现了类似的问题，但是PID完全不显示，core页面直接闪退了。求大佬指点(o゜▽゜)o

**Comment by NJUxianyu** [comment]
> ![image](https://private-user-images.githubusercontent.com/62581450/296136770-2c6c5261-0f0c-4af4-8e40-66064b651ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyODQ2NDQsIm5iZiI6MTcwODI4NDM0NCwicGF0aCI6Ii82MjU4MTQ1MC8yOTYxMzY3NzAtMmM2YzUyNjEtMGYwYy00YWY0LThlNDAtNjYwNjRiNjUxYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE5MjU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZTdjYWVmNGU1NjM3MDc4MGU4MzM1N2ViMTI1ZTZlZjgyYThmYmNhNWEyMDAzYzI1YjgzZDMwMjY2MWE1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCmoX6ycrKRiq-2mgvnFh3L0po-FLRytnXx78S_z0vo) 出现了类似的问题，但是PID完全不显示，core页面直接闪退了。求大佬指点(o゜▽゜)o

解决了吗？我也是这个问题
