### ISSUE TITLE
是否可以添加其它系统的适配？

### ISSUE THREAD

**Issue by xiaosuyyds** [rhwong/qsign-onekey#49]
请问，是否可以添加其它系统的适配，比如Liunx系统，大多数的服务器并非使用windows系统，而是Liunx或者其它系统，如果可以添加其它系统的适配，会让机器人在服务器的部署变得更加方便

**Comment by rhwong** [comment]
Linux可不这么觉得，Linux认为你应该去用docker版本XD

**Comment by rhwong** [comment]
哦对了 Linux下似乎有性能损失，如果没什么必须性，还是用Windows最好。
