### ISSUE TITLE
Qsign在GO-CQ登录过程中闪退（write file error）

### ISSUE THREAD

**Issue by YuukyuuKikan** [rhwong/qsign-onekey#50]
![QQ截图20231118141750](https://github.com/rhwong/qsign-onekey/assets/13735190/99aaf471-7824-44bd-b5e2-ec309a05e67f)
如图所示
Qsign版本号：1.2.3.1
Android Pad QQ版本：8.9.83

jar文件通过winrar解压测试报告没发现问题，已经关闭了系统所有的杀毒软件/防火墙。

**Comment by rhwong** [comment]
请不要使用高于1.1.9的版本
事实上后续不管是官方还是非官方维护的高于1.1.9的版本均会出现超出预期的错误。
包括不限于代码无限循环、签名不工作、go-cqhttp异常退出等。
并且在使用高于8.9.73的协议时，出现任何异常均为正常现象，请不要惊慌。
大部分情况下你需要做的是重启sign并重新登录。
