### ISSUE TITLE
启动后会频繁跳出openJDK停止工作

### ISSUE THREAD

**Issue by baiguiyuan7yue** [rhwong/qsign-onekey#51]
![IMG_2373](https://github.com/rhwong/qsign-onekey/assets/50880004/5d02f8eb-80dd-48f2-b8db-a543a121337e)
![IMG_2372](https://github.com/rhwong/qsign-onekey/assets/50880004/33e5189b-d01b-4a11-8cea-f24f1fca64f4)
qsign版本1.1.9bitterest，客户端版本是8.9.83和8.9.85，遇到过两种错误，姑且之前的版本全都不能用只有这俩能登陆，但是一登录就出问题，后一个错误还有好多errorlog

**Comment by rhwong** [comment]
目前8.9.83还可以用，但当版本大于8.9.78时是不受到qsign支持的。
已知版本越新，检测机制越多，出现的问题越多，包括不限于qsign去世、qsign不完全去世，连带go-cqhttp去世、临时端口超出最大值、内存溢出等。
出于法律原因，当前qsign已经停止开发和支持。若稳定性过低，请选用其他方案。

**Comment by Momona0v0** [comment]
这里使用8.9.88出现了同样的情况，今天看了以后改用8.9.78版本登录，可以正常运行，至少是不会openjdk停止工作了
当然具体能活多久还不知道
