### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by UncleYULE** [rhwong/qsign-onekey#53]
我第一次启动的时候不小心×掉了另一个窗口导致现在一直卡死在一个进程怎么办？
unidbg-fetch-qsign-onekey Ver.2023-11-06 by rhwong shia kagangtuya-star
txlib_Version is 8.9.88
If you want to change txlib_version , please delete [txlib_version.json]
-------------------------------------------------------------------------------------------------
Sync protocol version to go-cqhttp data folder.
子目录或文件 data\versions 已经存在。
已复制         1 个文件。
已复制         1 个文件。
-------------------------------------------------------------------------------------------------
The [config.yml] already contains account information or not exist.
Skip account settings.
-------------------------------------------------------------------------------------------------
Qsign API:http://127.0.0.1:13579
KEY=1145141919810
Qsign_version:2023-11-06
TXlib_version:8.9.88
-------------------------------------------------------------------------------------------------
Check if the curl command is installed in the environment variables...
The curl command is detected, use the installed curl
Qsign API is not running, Restarting...
Qsign API running on processes with PID:.

**Comment by rhwong** [comment]
没看懂，重开不就行了
实在不行，删掉txlib_version 重新部署不就行了？
