### ISSUE TITLE
error: sign_tail_manager.h tryRequestTail 

### ISSUE THREAD

**Issue by zwa73** [rhwong/qsign-onekey#54]
在txlib=8.9.85 启动时，bot发送消息时出现类似于以下信息是否正常？

tryRequestTail
curStatus is x duration y

以下是一段1.2.0版本qsign+8.9.90txlib的报错，和119+8985大差不差
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 11
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 15
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 17
[FEKit_]info: qq_sign.h:157 [GetSign] cmd:MessageSvc.PbSendMsg
[FEKit_]error: sign_tail_manager.h:147 tryRequestTail
[FEKit_]error: sign_tail_manager.h:166 curStatus is 1 duration 27

gocq可以正常发送消息，没有提示错误
我使用的是go-cq v1.2.0

**Comment by rhwong** [comment]
txlib＞8.9.78时，不受到qsign支持，一切错误均无法得到修正，且会出现其他诸多问题。详见其他issue。
