### ISSUE TITLE
当 host 设为 0.0.0.0 时会无限重启 qsign-onekey-core

### ISSUE THREAD

**Issue by lcx1969001** [rhwong/qsign-onekey#56]
因为有远程连接的需求，所以把 host 设为了 0.0.0.0
当 host 设为 0.0.0.0 时会无限重启 qsign-onekey-core
Start_Qsign.bat 版本：2023-11-06

**Comment by rhwong** [comment]
我猜测是curl会去访问0.0.0.0，这部分没有设计它去访问localhost
我稍后修一下。
