### ISSUE TITLE
有时崩溃后不能正常重启，而是一直卡在了如下图所示的弹窗页面

### ISSUE THREAD

**Issue by byx2020** [rhwong/qsign-onekey#59]
![image](https://github.com/rhwong/qsign-onekey/assets/58938653/e8136480-24fc-418f-a3d0-e96af6817df9)

以下为运行环境信息：
服务器配置：4C4G
操作系统：Windows Server 2012 R2 DataCenter 64bitCN
qsign-onekey版本：1.19b6(2023-12-19)
使用的协议版本：8.9.83
其他说明：如果大佬需要更多信息或协助，也可以让我进行提供

可能与问题 https://github.com/rhwong/qsign-onekey/issues/58 有关联，因为每次连续发送两条消息时，出现上图所示情况的概率会大幅度增加，不过问题 https://github.com/rhwong/qsign-onekey/issues/58 里面没有提到会卡住的问题。

**Comment by luosheng520qaq** [comment]
建议自行搭建qsign 我这边自行搭建并且使用自己安装的java21之后没有出现如此的性能与兼容问题

**Comment by byx2020** [comment]
> 建议自行搭建qsign 我这边自行搭建并且使用自己安装的java21之后没有出现如此的性能与兼容问题
@luosheng520qaq  大佬的意思是我的java版本太低了需要升级吗？

**Comment by luosheng520qaq** [comment]
一件包使用的是自带的java环境 可能存在兼容性问题 不是你电脑环境版本低 你单独升级系统环境也是没有用的 所以在作者解决问题重新发包之前建议自行搭建

**Comment by byx2020** [comment]
> 一件包使用的是自带的java环境 可能存在兼容性问题 不是你电脑环境版本低 你单独升级系统环境也是没有用的 所以在作者解决问题重新发包之前建议自行搭建

@luosheng520qaq  好的，了解了，感谢指点，我晚点去试试效果

**Comment by rhwong** [comment]
事实上，你可以在脚本里指定启动的java环境为本地，这样也可以使用本地java。
https://github.com/rhwong/qsign-onekey/blob/b72865f6daa32ca14119ce540aefb40af5ab3a06/Start_Qsign.bat#L4C7-L4C7

**Comment by rhwong** [comment]
https://github.com/rhwong/qsign-onekey/releases/tag/1.1.9-b7

**Comment by byx2020** [comment]
![image](https://github.com/rhwong/qsign-onekey/assets/58938653/19c7d548-63fb-49aa-8cd8-64234b21b77a)
话说我这边在使用了64位的java21之后，还是有这个问题，
不过现在平均一天大概只会卡住一两次了，出现问题的频率比之前下降了不少，
主要想问一下，还有那些可能的原因会导致这种卡住的情况，我想尝试一下能否完全解决这个问题，
如果两位大佬有时间的话，希望能够提供一下解决问题的方向，不胜感激
@rhwong @luosheng520qaq

**Comment by rhwong** [comment]
>......希望能够提供一下解决问题的方向，不胜感激

需要修改上游unidbg

**Comment by rhwong** [comment]
https://github.com/rhwong/qsign-onekey/issues/64#issuecomment-1953401635
