### ISSUE TITLE
可否添加中文日志

### ISSUE THREAD

**Issue by xiaosuyyds** [rhwong/qsign-onekey#60]
有时候英文日志太复杂看起来很麻烦还要翻译，是否可以添加以下中文版本的日志

**Comment by rhwong** [comment]
因为有些系统版本比较脑瘫，编码方式有问题，用中文会出乱码。（但是在其他系统又正常）所以才以英文的方式写。
总共就那几句话，克服一下！

**Comment by xiaosuyyds** [comment]
我之前尝试自己弄中文版本，可是就是一直卡在编码问题上……windows的编码方式还真是神奇了，我在弄的时候查到一个命令好像可以解决问题:chcp 65001

**Comment by rhwong** [comment]
> 我之前尝试自己弄中文版本，可是就是一直卡在编码问题上……windows的编码方式还真是神奇了，我在弄的时候查到一个命令好像可以解决问题:chcp 65001

有些机依然不管用。相信我。
Windows的bat就是一坨。

**Comment by rhwong** [comment]
这个只是强制UTF8
既然是中文，你还不如强制GBK
chcp 936

**Comment by xiaosuyyds** [comment]
有道理

**Comment by rhwong** [comment]
不保证泛用性。

**Comment by xiaosuyyds** [comment]
感谢大佬！

**Comment by rhwong** [comment]
讲个故事，用不了
传到GitHub上的文件会被自动转码

**Comment by rhwong** [comment]
本地是CRLF，传到GitHub上会变成Unix
🤣

**Comment by xiaosuyyds** [comment]
啊？

**Comment by xiaosuyyds** [comment]
我有一招，可以把bat打包为exe

**Comment by xiaosuyyds** [comment]
这样就没有编码的问题了

**Comment by rhwong** [comment]
没有意义。我直接打包zip也可以。
问题在于git push的默认设置。
别担心，让我来修改本地git的策略解决这个问题。

**Comment by xiaosuyyds** [comment]
嗯

**Comment by rhwong** [comment]
可以了

**Comment by xiaosuyyds** [comment]
好耶！
