### ISSUE TITLE
请问该项目使用的是什么开源协议，我能将它集成至我的项目里吗?

### ISSUE THREAD

**Issue by xufuyu** [rhwong/qsign-onekey#61]
请问该项目使用的是什么开源协议，我能将它集成至我的项目里吗?
What open source license does the project use, and can I integrate it into my project?

我想做一个多协议集成的QQ机器人一键启动程序，以方便小白和开发者快速登录QQ机器人帐户并切换协议.
I want to make a multi-protocol integrated QQ robot one-click launcher, in order to facilitate Xiaobai and developers to quickly log in to QQ robot accounts and switch protocols.

现在缺少协议库，这是一个不错的项目。
Now the protocol library is missing, which is a nice project.

Thanks!

**Comment by rhwong** [comment]
二进制文件请参照原项目
脚本部分无协议，可以任意使用。
如果可以，最好在可以看到的地方著明使用过本项目，感激不尽。

**Comment by rhwong** [comment]
二进制文件请参照原项目
脚本部分无协议，可以任意使用。
如果可以，最好在可以看到的地方著明使用过本项目，感激不尽。

**Comment by xufuyu** [comment]
我会在项目说明中著名使用了本项目



***@***.***
 
发件人： 贰狐
发送时间： 2024-01-26 11:20
收件人： rhwong/qsign-onekey
抄送： Evan; Author
主题： Re: [rhwong/qsign-onekey] 请问该项目使用的是什么开源协议，我能将它集成至我的项目里吗? (Issue #61)
二进制文件请参照原项目
脚本部分无协议，可以任意使用。
如果可以，最好在可以看到的地方著明使用过本项目，感激不尽。
