### ISSUE TITLE
Qsgin异常重启

### ISSUE THREAD

**Issue by xiaosuyyds** [rhwong/qsign-onekey#64]
在Qsgin签名的时候可能会卡死一小会，但此时端口仍旧占用，导致守护进程误以为Qsgin死机了重启新的，但是无法关闭原先的进程，新启动的Qsgin会因为端口占用的问题立马报错而退出（大概是这样）。但是过一会原来的Qsgin就恢复了，没什么影响，就是在登陆的时候弹窗很烦……可不可以修复一下，改善一下守护进程检测的逻辑（？）

**Comment by avexova** [comment]
你这个还算不错了...我遇到的是java报错弹窗....Qsgin已经没法工作，但是他又没法结束报错的java窗口，导致就算检测到了也没法重启...

**Comment by xiaosuyyds** [comment]
> 你这个还算不错了...我遇到的是java报错弹窗....Qsgin已经没法工作，但是他又没法结束报错的java窗口，导致就算检测到了也没法重启...

这个我也遇到过，直接报错拒绝访问，然后Qsgin就崩溃了……

**Comment by avexova** [comment]
蠢办法是有的，建立一个定时运行的脚本，检测结束 名为WerFault.exe的进程任务就行。这个就是上面的错误无视。
文本写个  *.bat
内容：
taskkill /f /fi "imagename eq WerFault.exe" /fi "windowtitle eq OpenJDK Platform binary"

**Comment by rhwong** [comment]
> 在Qsgin签名的时候可能会卡死一小会，但此时端口仍旧占用，导致守护进程误以为Qsgin死机了重启新的，但是无法关闭原先的进程，新启动的Qsgin会因为端口占用的问题立马报错而退出（大概是这样）。但是过一会原来的Qsgin就恢复了，没什么影响，就是在登陆的时候弹窗很烦……可不可以修复一下，改善一下守护进程检测的逻辑（？）

卡死一小会儿这个问题我没听到过更多反馈。考虑是硬件配置问题或者是系统问题？
因为在2c2g的云服务器都没遇到过这种情况。

**Comment by rhwong** [comment]
请高于83版本的尝试一下1.1.6版本
https://github.com/rhwong/qsign-onekey/releases/tag/240220
#66 #65 #46 #59

**Comment by xiaosuyyds** [comment]
好耶，换了1.1.6版本基本没遇到过什么bug了（喜）
