### ISSUE TITLE
qsign天天异常关闭,这个事情有办法解决么,一关闭就导致收发不及时

### ISSUE THREAD

**Issue by lizheyo77** [rhwong/qsign-onekey#65]
腾讯作妖,
前几天我没断电之前一个月qsign一直没问题,
前天断电以后
qsign天天异常关闭,这个事情有办法解决么,一关闭就导致收发不及时
目前85.90协议都有这个问题

**Comment by rhwong** [comment]
83以上都会这样。 #58

**Comment by rhwong** [comment]
https://github.com/rhwong/qsign-onekey/issues/64#issuecomment-1953401635
