### ISSUE TITLE
无限重启

### ISSUE THREAD

**Issue by NJUxianyu** [rhwong/qsign-onekey#66]
![image](https://github.com/rhwong/qsign-onekey/assets/100936313/40828681-ba99-48be-824b-ffa4d4cfb4bc)
一路回车，使用的是1.2.0版本的go-cqhttp。不停的有新窗口启动，但总是被秒关。

**Comment by rhwong** [comment]
88版本协议文件有问题。等我发个新的包。

**Comment by rhwong** [comment]
https://github.com/rhwong/qsign-onekey/issues/64#issuecomment-1953401635
