### ISSUE TITLE
麻烦问一下

### ISSUE THREAD

**Issue by 2055135** [rhwong/qsign-onekey#68]
![image](https://github.com/rhwong/qsign-onekey/assets/119772101/043e9c4e-af52-48c5-87cc-126b9a895f59)
zhe'g这个是哪里出了问题啊？

**Comment by rhwong** [comment]
八成是sign死了 关了核心进程，让它重启一下qsign

**Comment by 2055135** [comment]
> 八成是sign死了 关了核心进程，让它重启一下qsign

但是重启后第一次能签上，后面又出现这问题
