### ISSUE TITLE
佬，新的协议版本还会更新吗？

### ISSUE THREAD

**Issue by XiaoFuOS** [rhwong/qsign-onekey#72]
比如9开头的版本

**Comment by rhwong** [comment]
不兼容 试过了

**Comment by keqingyyds** [comment]
> ```
>   # 服务器可使用docker在本地搭建或者使用他人开放的服务
>   sign-servers: 
>     - url: 'http://ddns.trpgbot.com:14531/'
>       key: 'txsb233'
>       authorization: '-'
>   auto-register: true
> ```
> 
> 9.0.56的

失效了
