### ISSUE TITLE
现在code45还有没有别的路子

### ISSUE THREAD

**Issue by keqingyyds** [rhwong/qsign-onekey#73]
有偿也找不到解决问题方案，hoshinbot挂不了别的客户端
头疼死了

**Comment by rhwong** [comment]
Jump to [LLOneBot/LLOneBot](https://github.com/LLOneBot/LLOneBot)
@Himeno-Yumemi Himeno-Yumemi 
@keqingyyds

**Comment by rhwong** [comment]
If you use Hoshino
You can also try [OpenShamrock](https://github.com/whitechi73/OpenShamrock)
